DROP TABLE IF EXISTS tbl_student;
create table tbl_student(
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
  course_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '课程ID',
  agency_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '所属机构',
  id_number VARCHAR(32) NOT NULL DEFAULT '' COMMENT '身份证号',
  student_name VARCHAR(16) NOT NULL DEFAULT '' COMMENT '学生姓名',
  student_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '学生编号',
  gender TINYINT NOT NULL DEFAULT 0 COMMENT '0-男,1-女',
  nationality VARCHAR(16) NOT NULL DEFAULT '' COMMENT '民族',
  birthday DATETIME DEFAULT NULL COMMENT '生日',
  physical_condition VARCHAR(16) NOT NULL DEFAULT '' COMMENT '身体状况',
  marital_status TINYINT NOT NULL DEFAULT 0 COMMENT '婚姻状态 0-未婚,1-已婚,2-离异',
  political_outlook VARCHAR(16) NOT NULL DEFAULT '' COMMENT '政治面貌',
  insured_status TINYINT NOT NULL DEFAULT 0 COMMENT '参保状态 0-参保,1-未参保',
  mobile VARCHAR(16) NOT NULL DEFAULT '' COMMENT '联系电话',
  email VARCHAR(64) NOT NULL DEFAULT '' COMMENT '邮箱',
  work_status TINYINT NOT NULL DEFAULT 0 COMMENT '失业状态',
  fingerprint VARCHAR(1024) NOT NULL DEFAULT '' COMMENT '存储指纹信息，暂定哈希值',
  education VARCHAR(32) NOT NULL DEFAULT '文化水平',
  profession VARCHAR(32) NOT NULL DEFAULT '专业',
  graduation_school VARCHAR(64) NOT NULL DEFAULT '' COMMENT '毕业学校',
  registered_residence VARCHAR(32) NOT NULL DEFAULT '' COMMENT '户口所在地',
  registered_property VARCHAR(32) NOT NULL DEFAULT '' COMMENT '户口性质',
  status TINYINT NOT NULL DEFAULT 0 COMMENT '状态 0-正常,1-已删除',
  bank VARCHAR(64) NOT NULL DEFAULT '' COMMENT '开户行',
  bank_account VARCHAR(64) NOT NULL DEFAULT '' COMMENT '银行账户',
  bank_account_name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '银行户名',
  school_date DATETIME DEFAULT NULL COMMENT '入学日期',
  student_cat VARCHAR(32) NOT NULL DEFAULT '' COMMENT '人员类别',
  tuition DECIMAL(10,2) NOT NULL DEFAULT 0.00 COMMENT '缴纳学费',
  subsidy_code VARCHAR(32) NOT NULL DEFAULT '' COMMENT '补贴标准',
  subsidy_target VARCHAR(32) NOT NULL DEFAULT '' COMMENT '支付对象',
  is_dropout TINYINT NOT NULL DEFAULT 0 COMMENT '0-否，1-是',
  dropout DATETIME  DEFAULT NULL COMMENT '退学日期',
  has_certificate TINYINT NOT NULL DEFAULT 0 COMMENT '0-无，1-有',
  certificate_level VARCHAR(32) NOT NULL DEFAULT '' COMMENT '培训证书等级',
  certificate VARCHAR(32) NOT NULL DEFAULT '' COMMENT '证书名称',
  is_using_coupon TINYINT NOT NULL DEFAULT 0 COMMENT '是否使用培训券 0-否,1-是',
  coupon_num VARCHAR(64) NOT NULL DEFAULT '' COMMENT '培训券码',
  is_compact TINYINT NOT NULL DEFAULT 0 COMMENT '是否企业录用员工,0-否，1-是',
  compact VARCHAR(32) NOT NULL DEFAULT '' COMMENT '合同期限,存储为年',
  create_time DATETIME NOT NULL DEFAULT current_timestamp COMMENT '创建时间',
  update_time DATETIME NOT NULL DEFAULT current_timestamp ON UPDATE current_timestamp COMMENT '更新时间',

  PRIMARY KEY id(id),

  UNIQUE KEY uniq_student_id(student_id)
) ENGINE = innodb DEFAULT CHARSET =utf8mb4 COMMENT '考勤表';